-keep class androidx.media3.** { *; }
-keep class com.tunifyx.app.data.model.** { *; }
-keep class com.tunifyx.app.data.api.** { *; }
-keepattributes Signature
-keepattributes *Annotation*
-dontwarn okhttp3.**
-dontwarn retrofit2.**
